version: '3.8'
services:
  mysql:
    # Thay build bằng image từ Docker
    image: lamiee/workoutplanner-mysql:latest
    container_name: workoutplanner
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workoutplanner
      MYSQL_USER: lamiee
      MYSQL_PASSWORD: lamiee

    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    #      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: